apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crossplane-crds
  namespace: argocd
  labels:
    me.kundun: crossplane-crds
spec:
  generators:
    - git:
        repoURL: 'https://github.com/luminosita/k8s-cluster-talos'
        revision: keycloak
        directories:
          - path: k8s/infra/crossplane-crds/*
  template:
    metadata:
      name: 'crossplane-crds-{{ path.basename }}'
      labels:
        me.kundun: crossplane-crds
    spec:
      project: crossplane-crds
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/luminosita/k8s-cluster-talos
        targetRevision: keycloak
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
